### ISSUE TITLE
Scaling broken at 1366x768 resolution or below

### ISSUE THREAD

**Issue by DeathWrench** [AHeroicLlama/Mappalachia#25]
I have this set like so in windows display settings:
![image](https://cdn.discordapp.com/attachments/515842332201975821/853606239522652190/unknown.png)

this causes Mappalachia to be unusable:
![image](https://cdn.discordapp.com/attachments/515842332201975821/853606162095407124/unknown.png)

how it looks scaled to 100%:
![image](https://cdn.discordapp.com/attachments/515842332201975821/853605932818497536/unknown.png)

running app while scaling is set to 100% and then setting it to 150%:
![image](https://cdn.discordapp.com/attachments/515842332201975821/853606097806295061/unknown.png)

150% with override high dpi checked:
![image](https://user-images.githubusercontent.com/45341450/121806696-e94aa300-cc1e-11eb-8561-7b9087483d70.png)

**Comment by AHeroicLlama** [comment]
Thanks for the report - I'm unable to recreate this exact issue on my machine, and DPI scaling appears to work correctly.

Can you confirm a few further things for me please so that I can recreate and debug;
- Are you using any other DPI or accessibility settings which differ from a default Win10 installation?
- Are you using any third party apps which affect scaling or visibility?
- What Mappalachia version are you using? Latest version is 1.3.2.0
- What is your Windows 10 version? (EG 20H2)
- Does the map image ever load? What is the behaviour when you plot items on the map? I notice that it is black in _all_ your screenshots, which isn't normal and may be another symptom of the same problem
- What happens when you resize Mappalachia to be fullscreen? Does the search results table appear properly?
- Besides the search results being too small, are there any other issues that make it 'unusable'?

Thanks

**Comment by DeathWrench** [comment]
My apologies, I left out that there is no issues with the map, I just put a black.jpg in there so I could add an alpha mask and pull those icons out. I'll test the various things and report back.

**Comment by AHeroicLlama** [comment]
Thanks - okay so it's a matter of using a pretty low resolution.
This is tricky to fix but at least I can recreate now.
Can you confirm your _native/normal_ resolution please? I know you said you set it to 1360x768

**Comment by DeathWrench** [comment]
1920x1080 but I do have my computer plugged into a TV rather than a monitor.

**Comment by AHeroicLlama** [comment]
Got it - so you're using 1920x1080, except the 150% scaling therefore makes it equivalent to 1280x720.
Mappalachia doesn't properly resize at these low resolutions, so it basically just needs to support low resolutions.
I think I have everything I need to recreate now - thank you.

**Comment by AHeroicLlama** [comment]
Thanks again for the report - this has now been resolved
