### ISSUE TITLE
Copy map to clipboard

### ISSUE THREAD

**Issue by skyhirider** [AHeroicLlama/Mappalachia#59]
Would it be possible for you to add a copy to clipboard option in one of the menus or make Ctrl + C work and copy the current map? 

Ideally in a format that is optimized for Discord (can't upload more than 8mb)

And thank your for the Cluster setting, its amazing, helped me find a few hotspots for herbs that I did not know existed. A very good update!

**Comment by AHeroicLlama** [comment]
Hiya, interesting idea! While it seems straight forward at first, it turns out there are actually some challenges with copying images in the Windows clipboard and getting them into Discord.

By default, Mappalachia will lightly compress images once saved _to disk_, specifically with that 8MB limit in mind - however when you place an image on the windows clipboard it is converted to raw bitmap, massively inflating the file size. Therefore, this only works for some images if we drop the 4k*4k image way down to 1k*1k. It works, but the text becomes very hard to read and it's not the experience I'd want from Mappalachia.

The second idea I had would be copying a temp image _file_ to the clipboard - turns out Discord doesn't accept pastes of files either, only drag and drops.

So, the compromise I have is that such a quick-save function saves the image with recommended settings and default file name, then opens the file explorer for you at that file. It's shortcutted as ctrl-shift-s and also in the Map menu. (Ctrl-c is a bad idea because of conflict with copying out of text field). I've also added a new checkbox in the file export menu to also select the file in explorer after.

If you have any other comments or feedback please let me know, I'm always happy to implement new features if they sound good to me, which this did. - I'm happy to hear the cluster plot is well received!

Commits
6d2afd850a8d3764dd9fcb40b97891eefe8fa013
9cd7b948c54ace2336b7ed5761cf8dc94668550a

**Comment by skyhirider** [comment]
Thanks for the quick response and implementation! 

Will make it a lot easier when a friend asks where is X and I can quickly boot up your tool, get the data out an share.

I also did a quick search and seems there is a possibility to use custom clipboard formats, thou not sure if that would work for this case https://docs.microsoft.com/en-us/cpp/mfc/clipboard-adding-other-formats?view=msvc-170

**Comment by AHeroicLlama** [comment]
Hope it helps! Realistically it may be a while before it releases as I would likely wait for another feature or game patch before pushing an otherwise small update to all users.

Regarding custom clipboard formats, I'll be honest, that looks beyond my experience level at the moment. It touches the Windows API almost directly and the documentation here is ... loose.

Also I assume Discord would not be able to interpret a custom clipboard format anyway.

**Comment by AHeroicLlama** [comment]
QuickSave feature + 'show in explorer' save dialog option released with v1.6.1.0 (PR https://github.com/AHeroicLlama/Mappalachia/pull/60)
