### ISSUE TITLE
Support 8k Maps

### ISSUE THREAD

**Issue by superelitist** [AHeroicLlama/Mappalachia#62]
I'm trying to create some ore vein layers to add to the 8192x8192 map I use, but the minimum size for each icon is still too large--the inner crosshairs are rather blurry, even on the smallest size, and they overlap sometimes, making it hard to identify/count particular veins.

Ideally, a true solution would probably be for Mappalachia to support loading 8k images natively, but also and more simply perhaps consider allowing smaller icon sizes, and/or even a single pixel dot--or maybe just allow users to load their own images to use as icons?

**Comment by AHeroicLlama** [comment]
Unfortunately Mappalachia was only designed ground-up for 4k images because this is the native resolution of the in-game maps. Any higher resolution I considered superfluous. It was also not designed to be used as a replacement for in-game maps nor support other maps than those it comes with.

Due to this, I can't justify the work to support different resolutions for the relatively low benefit it provides to the overall user base. I would encourage a pull request.

Having said that, have you also tried adjusting the Icon Width setting? The minimum setting here goes right down to 1px (it may blend over multiple if its coordinate is not an exact center of pixel however).
