### ISSUE TITLE
[Feature Request] Export only plots

### ISSUE THREAD

**Issue by MotiasNotMe** [AHeroicLlama/Mappalachia#80]
What I suggest:
Add the ability to export/save plots without the map itself

Why this is needed:
I only needed to output the location of the dots, which I then wanted to process in another program.
_So I created a jpg with black solid color and save._

How this could be done:
1) Add the ability to uncheck a map is selected
2) Allow the brightness to be set to 0%
2) Add a simple black map (my way)
3) Add the ability to "Export plots only"
As (jpg on black background or png with alpha channel)

**Comment by AHeroicLlama** [comment]
Hi, great idea thank you. I've implemented this under 2a74658687b53a17928d85fc577ec288db81501f and will be looking to include it in the next release, most likely alongside the next game update.

The implementation adds a new background image option, 'None' which removes any background image, replacing it with a transparent bitmap. The auto-recommended export file type is also changed to PNG to ensure the transparency persists, otherwise it will be black. I think that achieves what you wanted here. Thanks
