### ISSUE TITLE
[Feature Request] Plot Style Settings: 

### ISSUE THREAD

**Issue by MotiasNotMe** [AHeroicLlama/Mappalachia#81]
My suggestion:
1)Add the ability to save custom color palettes.

2)Add the ability to change the order of colors in the current palette, for example:
palette:
[red yellow white]
_for example, I want to change 1st color, for that I need to remove ALL colors and re-select it is inconvenient._

3)Add the ability to import and use your own shapes/shapes library as plots.

**Comment by AHeroicLlama** [comment]
Thanks for the ideas,

1) I like this but I'm conscious of overcomplicating the UI/functionality of plot customisation further than it already is. This probably requires further thought. Please expand if you have any further comments. I've not had any other requests for such a feature so the benefit/effort seems low.

2) I agree - the windows forms UI element doesn't seem to natively allow this but I will definitely investigate, rearranging colours is clunky at present. Alternatively, there may be scope to rework the way colours/shapes are _assigned_ (For example allow the user to select a colour/shape for each legend group?). It's something I'll have a play with when I find time and see if I can get any prototypes that feel right before agreeing to implement.

3) Custom shapes don't seem feasible - there is no mechanism or format/language I can imagine in which users can easily define shapes which would still work in a way which allows the shape to have dynamic size, thickness, and colour. The set of shapes in Mappalachia are all defined as literal lists of points/lines/curves which fit to a grid (That's why multiple shapes selected on top of each other still look quite natural). Without entirely gutting the way shapes work, I believe this probably isn't viable.

**Comment by AHeroicLlama** [comment]
Closing this as it has overlap with other feature requests now raised:

For:

1. Please see #113  for an approximately similar request. As I have still not had any more requests for your specific feature however, I don't plan to implement as specifically described here.
2. Please see #112  which will achieve this.
3. As above, this won't be considered

Thank you
