### ISSUE TITLE
Opossums on map

### ISSUE THREAD

**Issue by skyhirider** [AHeroicLlama/Mappalachia#98]
I've searched for opossums and only found 10 spawns in total, which seems extremely low, considering some videos are reporting the critters on other locations.

Is your map accurate? And could you add opossums and other critters to the npc search list?

**Comment by AHeroicLlama** [comment]
Thanks, this is actually a fairly complex question. It's more to do with how Bethesda structured the data rather than missing data.

Critters in FO76 are a weird unique subset of how NPCs work - so they don't appear in Mappalachia's variable NPC spawns list. But they also don't appear when searching by direct names as you have here.

I believe if you search "critter" in the standard search field, and then map results for "CritterA" and "CritterB", this will largely give you what you need. These "Critter" NPC entities can spawn one of many critters (foxes, opossums, frogs, etc). The available spawns in the pool may also be based on the region of the map.

As a side note, the 10 results you found will be the only 10 "hardcoded" (guaranteed) spawns, with all others being from the critter "pool".

Hope that helps!

**Comment by skyhirider** [comment]
Thanks, that does explain it. I'm wondering if a critter option in npc selection would make sense at all, judging by the fact its random

But I was able to generate a map with all critters, cheers!

**Comment by AHeroicLlama** [comment]
I believe I'd explored this idea before, for whatever reason I didn't conclude with anything I felt I could release. I appreciate the suggestion anyhow though, I'll add it to my list to re-review if something like this could be done, although I won't promise it any time soon.
